# Generated by Django 3.2.6 on 2021-08-06 14:35

from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='名称')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '图片类别',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '视频分类',
                'verbose_name_plural': '视频类别',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='视频名称')),
                ('url', models.CharField(max_length=256, verbose_name='视频链接')),
                ('url_code', models.CharField(max_length=20, verbose_name='提取码')),
                ('image', models.ImageField(upload_to=web.models.upload_to_video, verbose_name='视频图片')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.videocategory', verbose_name='视频分类')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('image', models.ImageField(upload_to=web.models.upload_to, verbose_name='图片')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.imgcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '上传图片',
                'ordering': ['-date_time'],
            },
        ),
    ]
