# Generated by Django 3.2.6 on 2021-08-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_video_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='音乐标题')),
                ('singer', models.CharField(max_length=50, verbose_name='歌手')),
                ('album', models.CharField(max_length=20, verbose_name='时长')),
                ('file', models.FileField(upload_to='music', verbose_name='音乐文件')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '上传音乐文件',
                'ordering': ['-c_time'],
            },
        ),
    ]
